[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9"
rand = "0.8.5"
hex = "0.4.3"
eth_trie = "0.4.0"
tiny-keccak = "2.0.2"